### ISSUE TITLE
Series / Operations

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/Pogues-Back-Office#165]
Default sql backup seems to contain series & operations but deployed instance thanks to Bowie do not contain fields in dropdowns.
Do we have to provide an other property to value them ? (it's actually impossible to create a new questionnaire without these informations)

**Comment by BulotF** [comment]
The script that initializes pogues bdd...
https://github.com/InseeFr/Bowie/blob/main/deploiement/Pogues/pogues-bdd-backup.sql

**Comment by nsenave** [comment]
When deploying Pogues from [Bowie's helm chart](https://github.com/InseeFr/Helm-Charts/tree/main/charts/bowie), we currently use an Postgres dump file in the values as such:

```yaml
pogues:
  ui:
    # ...
  api:
    # ...
  postgresql:
    # ...
    primary:
      initContainers:
        - name: import-dump
          image: busybox
          command:
            [
              "wget",
              "https://raw.githubusercontent.com/InseeFr/Bowie/main/deploiement/Pogues/pogues-bdd-backup.sql",
              "--output-document=/import/backup.sql",
            ]
          volumeMounts:
            - mountPath: /import
              name: import-volume
      extraVolumes:
        - name: import-volume
          emptyDir: {}
      extraVolumeMounts:
        - name: import-volume
          mountPath: "/docker-entrypoint-initdb.d"
```

➡️ We could store these values in the [values file provided in the repo](https://github.com/InseeFr/Helm-Charts/blob/main/charts/bowie/values.yaml).

Any cleaner/better idea?
